#!/bin/sh
case $1 in
  post)
    sleep 5
    XRANDR_USER=`ps u | grep xrandr-brightness | cut -d" " -f1`
    [ ! -z "$XRANDR_USER" ] && sudo -u $XRANDR_USER $(which xrandr-brightness) apply
    ;;
esac
